apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cron
spec:
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongo-backup
            image: registry.cern.ch/cmsweb/mongo-backup
            args:
            - /bin/sh
            - -c
            - /root/backup.sh\
            volumeMounts:
            - name: openstack-secrets
              mountPath: /etc
          restartPolicy: Never
          volumes:
          - name: openstack-secrets
            secret:
              secretName: openstack-secrets