---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-auth
data:
  password: {{.Values.db.auth.password | b64enc}}
  keyfile: {{.Values.db.auth.keyfile | b64enc}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter-configmap
  namespace: monitoring
data:
  prometheus_adapter.yml: |
    rules:
        - seriesQuery: 'myapphttp_process_open_fds'
          resources:
            template: "<<.Resource>>"
          name:
            matches: "^(.*)"
            as: "${1}"
          metricsQuery: 'max(<<.Series>>) by (job)'
        - seriesQuery: 'myapphttp_process_cpu_seconds_total'
          resources:
            template: "<<.Resource>>"
          name:
            matches: "^(.*)"
            as: "${1}"
          metricsQuery: 'max(<<.Series>>) by (job)'
        - seriesQuery: 'myapphttp_established_connections'
          resources:
            template: "<<.Resource>>"
          name:
            matches: "^(.*)"
            as: "${1}"
          metricsQuery: 'max(<<.Series>>) by (job)'
        - seriesQuery: 'myapphttp_load1'
          resources:
            template: "<<.Resource>>"
          name:
            matches: "^(.*)"
            as: "${1}"
          metricsQuery: 'max(<<.Series>>) by (job)'
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-secrets
  namespace: monitoring
data:
{{ (.Files.Glob "files/prometheus-secrets/*").AsSecrets | indent 2 }}
---
