---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-auth
data:
  password: {{.Values.db.auth.password | b64enc}}
  keyfile: {{.Values.db.auth.keyfile | b64enc}}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodump-config
type: Opaque
  stringData:
    mongodump-config.cfg: |-
      password: {{.Values.db.auth.password | b64enc}}
      uri: mongodb://137.138.226.191/admin?replicaSet=cms-db1
      user: clusterAdmin

---
apiVersion: v1
kind: Secret
metadata:
  name: s3-config
type: Opaque
  stringData:
    s3-config.cfg: |-
      host_base = s3.cern.ch
      host_bucket = %(bucket)s.s3.cern.ch
      access_key = {{.Values.db.auth.password | b64enc}}
      secret_key = {{.Values.db.auth.password | b64enc}}
      use_https = True
---